Tune dev resources / autoscaling
elastic-ipfs/bitswap-peer-deployment pull request #54
Opened 2022-12-09 12:16 UTC by francardoso93

2022-12-09 13:07 UTC, blucas requested changes

2022-12-09 13:07 UTC, blucas commented on helm/values-dev.yaml
> +        periodSeconds: 5
```suggestion
        periodSeconds: 5
        timeoutSeconds: 1
        failureThreshold: 3
        successThreshold: 1
```

Let's be explicit about these settings so there is no confusion as to what each one is configured with.  The values I've set for `timeout`, `failure`, and `success` are the defaults kubernetes would set.

2022-12-09 13:07 UTC, blucas commented on helm/values-dev.yaml
> +        failureThreshold: 10
```suggestion
        failureThreshold: 10
        successThreshold: 1
```
Let's be explicit about these settings so there is no confusion as to what each one is configured with. The value I've set for `success` is the default kubernetes would set.

2022-12-09 13:14 UTC, blucas approved these changes

2022-12-09 13:15 UTC, ericssontadashi approved these changes

2022-12-14 12:46 UTC, francardoso93 commented
I'm waiting on definitions of changing the instance types for dev and staging before approving this

2022-12-14 15:23 UTC, francardoso93 commented
> I'm waiting on definitions of changing the instance types for dev and staging before approving this

https://github.com/elastic-ipfs/infrastructure/pull/191

2022-12-14 15:23 UTC, merged