reduced resources based on 30d behavior
elastic-ipfs/bitswap-peer-deployment pull request #63
Opened 2023-01-20 23:23 UTC by ericssontadashi

Reducing allocated resources for bitswap peer

![image](https://user-images.githubusercontent.com/2631225/213822357-1aa35d48-dee0-473a-8437-4b8ba910c6c9.png)

2023-01-23 12:32 UTC, francardoso93 requested changes
LGTM
We should also consider change instance type, we're currently using `c6i.2xlarge`, but this service is no longer CPU intensive

2023-01-23 12:33 UTC, francardoso93 approved these changes

2023-01-24 10:50 UTC, simone-sanfratello commented
Are the other envs (dev, staging) consistent with this change?

2023-06-12 21:24 UTC, olizilla commented
covered in #94

2023-06-12 21:24 UTC, closed without merging